root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/server/main.go"
  bin = "tmp/app"
  # Folders to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html", "env", "yaml", "yml", "json"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
  # Files/folders to watch in addition to go files
  include_dir = []
  # Delay before restarting the server after a file change
  delay = 1000 # ms
  # Stop running old binary before building new one
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this)
  send_interrupt = false
  # Kill delay (ignored if send_interrupt is false)
  kill_delay = 500 # ms
  # Log file for air
  log = "air_errors.log"

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
